function CombinedScalePrintStuffAllTogether(All)

%AD then 6 spaces then 10, 11
fprintf('Optimal Parameters              AD       |      C9orf72      |         GRN        |       MAPT\n');
fprintf('Epicentre:                  %s     %s     %s     %s\n',                             All{1}.Parameters.DiseaseEpicentres{All{1}.Parameters.ProteinLocation}, All{2}.Parameters.DiseaseEpicentres{All{2}.Parameters.ProteinLocation}, All{3}.Parameters.DiseaseEpicentres{All{3}.Parameters.ProteinLocation}, All{4}.Parameters.DiseaseEpicentres{All{4}.Parameters.ProteinLocation})
fprintf('Seed concentration:         %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.Seedsize, All{2}.Parameters.Seedsize, All{3}.Parameters.Seedsize, All{4}.Parameters.Seedsize);
fprintf('Extracellular Fraction:     %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.ExtracellularDiffusionFraction, All{2}.Parameters.ExtracellularDiffusionFraction, All{3}.Parameters.ExtracellularDiffusionFraction, All{4}.Parameters.ExtracellularDiffusionFraction);
fprintf('Extracellular Speed:        %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.ExtracellularDiffusionSpeed, All{2}.Parameters.ExtracellularDiffusionSpeed, All{3}.Parameters.ExtracellularDiffusionSpeed, All{4}.Parameters.ExtracellularDiffusionSpeed);
fprintf('FMRI Model:                 %10d      %10d          %10d           %10d\n',         All{1}.Parameters.FMRIspread, All{2}.Parameters.FMRIspread, All{3}.Parameters.FMRIspread, All{4}.Parameters.FMRIspread);
fprintf('FMRI WeightFraction:        %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NetworkDiffusionWeightFractionFMRI, All{2}.Parameters.NetworkDiffusionWeightFractionFMRI, All{3}.Parameters.NetworkDiffusionWeightFractionFMRI, All{4}.Parameters.NetworkDiffusionWeightFractionFMRI);
fprintf('FMRI WeightDistance:        %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NetworkDiffusionWeightDistanceFractionFMRI, All{2}.Parameters.NetworkDiffusionWeightDistanceFractionFMRI, All{3}.Parameters.NetworkDiffusionWeightDistanceFractionFMRI, All{4}.Parameters.NetworkDiffusionWeightDistanceFractionFMRI);
fprintf('FMRI SynapticFraction:      %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.SynapticTransferWeightFractionFMRI, All{2}.Parameters.SynapticTransferWeightFractionFMRI, All{3}.Parameters.SynapticTransferWeightFractionFMRI, All{4}.Parameters.SynapticTransferWeightFractionFMRI);
fprintf('FMRI SynapticDistance:      %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.SynapticTransferWeightDistanceFractionFMRI, All{2}.Parameters.SynapticTransferWeightDistanceFractionFMRI, All{3}.Parameters.SynapticTransferWeightDistanceFractionFMRI, All{4}.Parameters.SynapticTransferWeightDistanceFractionFMRI);
fprintf('DTI Model:                  %10d      %10d          %10d           %10d\n',         All{1}.Parameters.DTIspread, All{2}.Parameters.DTIspread, All{3}.Parameters.DTIspread, All{4}.Parameters.DTIspread);
fprintf('DTI WeightFraction:         %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NetworkDiffusionWeightFractionDTI, All{2}.Parameters.NetworkDiffusionWeightFractionDTI, All{3}.Parameters.NetworkDiffusionWeightFractionDTI, All{4}.Parameters.NetworkDiffusionWeightFractionDTI);
fprintf('DTI WeightDistance:         %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NetworkDiffusionWeightDistanceFractionDTI, All{2}.Parameters.NetworkDiffusionWeightDistanceFractionDTI, All{3}.Parameters.NetworkDiffusionWeightDistanceFractionDTI, All{4}.Parameters.NetworkDiffusionWeightDistanceFractionDTI);
fprintf('DTI SynapticFraction:       %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.SynapticTransferWeightFractionDTI, All{2}.Parameters.SynapticTransferWeightFractionDTI, All{3}.Parameters.SynapticTransferWeightFractionDTI, All{4}.Parameters.SynapticTransferWeightFractionDTI);
fprintf('DTI SynapticDistance:       %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.SynapticTransferWeightDistanceFractionDTI, All{2}.Parameters.SynapticTransferWeightDistanceFractionDTI, All{3}.Parameters.SynapticTransferWeightDistanceFractionDTI, All{4}.Parameters.SynapticTransferWeightDistanceFractionDTI);
fprintf('DCM Model:                  %10d      %10d          %10d           %10d\n',         All{1}.Parameters.DCMspread, All{2}.Parameters.DCMspread, All{3}.Parameters.DCMspread, All{4}.Parameters.DCMspread);
fprintf('DCM WeightFraction:         %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NetworkDiffusionWeightFractionDCM, All{2}.Parameters.NetworkDiffusionWeightFractionDCM, All{3}.Parameters.NetworkDiffusionWeightFractionDCM, All{4}.Parameters.NetworkDiffusionWeightFractionDCM);
fprintf('DCM WeightDistance:         %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NetworkDiffusionWeightDistanceFractionDCM, All{2}.Parameters.NetworkDiffusionWeightDistanceFractionDCM, All{3}.Parameters.NetworkDiffusionWeightDistanceFractionDCM, All{4}.Parameters.NetworkDiffusionWeightDistanceFractionDCM);
fprintf('DCM SynapticFraction:       %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.SynapticTransferWeightFractionDCM, All{2}.Parameters.SynapticTransferWeightFractionDCM, All{3}.Parameters.SynapticTransferWeightFractionDCM, All{4}.Parameters.SynapticTransferWeightFractionDCM);
fprintf('DCM SynapticDistance:       %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.SynapticTransferWeightDistanceFractionDCM, All{2}.Parameters.SynapticTransferWeightDistanceFractionDCM, All{3}.Parameters.SynapticTransferWeightDistanceFractionDCM, All{4}.Parameters.SynapticTransferWeightDistanceFractionDCM);
fprintf('Network Diffusion Speed:    %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NetworkDiffusionSpeed, All{2}.Parameters.NetworkDiffusionSpeed, All{3}.Parameters.NetworkDiffusionSpeed, All{4}.Parameters.NetworkDiffusionSpeed);
fprintf('Misfolding Rate:            %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NEURONMisfold, All{2}.Parameters.NEURONMisfold, All{3}.Parameters.NEURONMisfold, All{4}.Parameters.NEURONMisfold);
fprintf('Damage Rate:                %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NEURONDamage, All{2}.Parameters.NEURONDamage, All{3}.Parameters.NEURONDamage, All{4}.Parameters.NEURONDamage);
fprintf('Synaptic Effect:            %10d      %10d          %10d           %10d\n',         All{1}.Parameters.NEURONEffect, All{2}.Parameters.NEURONEffect, All{3}.Parameters.NEURONEffect, All{4}.Parameters.NEURONEffect);
fprintf('Neuron Diffusion Fraction:  %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NEURONDiffusion, All{2}.Parameters.NEURONDiffusion, All{3}.Parameters.NEURONDiffusion, All{4}.Parameters.NEURONDiffusion);
fprintf('Neuron Diffusion Speed:     %10.5f      %10.5f          %10.5f           %10.5f\n', All{1}.Parameters.NEURONDiffusionSpeed, All{2}.Parameters.NEURONDiffusionSpeed, All{3}.Parameters.NEURONDiffusionSpeed, All{4}.Parameters.NEURONDiffusionSpeed);
fprintf('Active Transport Fraction:  %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NEURONTransport, All{2}.Parameters.NEURONTransport, All{3}.Parameters.NEURONTransport, All{4}.Parameters.NEURONTransport);
fprintf('Synaptic Transfer Fraction: %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.Parameters.NEURONSynaptic, All{2}.Parameters.NEURONSynaptic, All{3}.Parameters.NEURONSynaptic, All{4}.Parameters.NEURONSynaptic);
fprintf('\n');
fprintf('Optimisation value:         %10.5f      %10.5f          %10.5f           %10.5f\n', All{1}.OptimizeMetric, All{2}.OptimizeMetric, All{3}.OptimizeMetric, All{4}.OptimizeMetric);
fprintf('ASY:                        %10.8f      %10.8f          %10.8f           %10.8f\n', All{1}.ASY, All{2}.ASY, All{3}.ASY, All{4}.ASY);
fprintf('TTNB:                       %10d      %10d          %10d           %10d\n', All{1}.TTNB, All{2}.TTNB, All{3}.TTNB, All{4}.TTNB);
fprintf('\n\n');

fprintf('Non-pathogenic protein spread\n');
fprintf('                          AD quantity           %% | C9orf72 quantity           %% | GRN quantity           %% | MAPT quantity           %%\n');
fprintf('Extracellular diffusion: %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadExtracellular,          100*All{1}.NormalSpreadExtracellular         /All{1}.TotalNormal, All{2}.NormalSpreadExtracellular,          100*All{2}.NormalSpreadExtracellular         /All{2}.TotalNormal, All{3}.NormalSpreadExtracellular,          100*All{3}.NormalSpreadExtracellular         /All{3}.TotalNormal, All{4}.NormalSpreadExtracellular,          100*All{4}.NormalSpreadExtracellular         /All{4}.TotalNormal);
fprintf('Weight FMRI:             %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightFMRI,             100*All{1}.NormalSpreadWeightFMRI            /All{1}.TotalNormal, All{2}.NormalSpreadWeightFMRI,             100*All{2}.NormalSpreadWeightFMRI            /All{2}.TotalNormal, All{3}.NormalSpreadWeightFMRI,             100*All{3}.NormalSpreadWeightFMRI            /All{3}.TotalNormal, All{4}.NormalSpreadWeightFMRI,             100*All{4}.NormalSpreadWeightFMRI            /All{4}.TotalNormal);
fprintf('Weight DTI:              %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightDTI,              100*All{1}.NormalSpreadWeightDTI             /All{1}.TotalNormal, All{2}.NormalSpreadWeightDTI,              100*All{2}.NormalSpreadWeightDTI             /All{2}.TotalNormal, All{3}.NormalSpreadWeightDTI,              100*All{3}.NormalSpreadWeightDTI             /All{3}.TotalNormal, All{4}.NormalSpreadWeightDTI,              100*All{4}.NormalSpreadWeightDTI             /All{4}.TotalNormal);
fprintf('Weight DCM:              %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightDCM,              100*All{1}.NormalSpreadWeightDCM             /All{1}.TotalNormal, All{2}.NormalSpreadWeightDCM,              100*All{2}.NormalSpreadWeightDCM             /All{2}.TotalNormal, All{3}.NormalSpreadWeightDCM,              100*All{3}.NormalSpreadWeightDCM             /All{3}.TotalNormal, All{4}.NormalSpreadWeightDCM,              100*All{4}.NormalSpreadWeightDCM             /All{4}.TotalNormal);
fprintf('Weight Distance FMRI:    %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightDistanceFMRI,     100*All{1}.NormalSpreadWeightDistanceFMRI    /All{1}.TotalNormal, All{2}.NormalSpreadWeightDistanceFMRI,     100*All{2}.NormalSpreadWeightDistanceFMRI    /All{2}.TotalNormal, All{3}.NormalSpreadWeightDistanceFMRI,     100*All{3}.NormalSpreadWeightDistanceFMRI    /All{3}.TotalNormal, All{4}.NormalSpreadWeightDistanceFMRI,     100*All{4}.NormalSpreadWeightDistanceFMRI    /All{4}.TotalNormal);
fprintf('Weight Distance DTI:     %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightDistanceDTI,      100*All{1}.NormalSpreadWeightDistanceDTI     /All{1}.TotalNormal, All{2}.NormalSpreadWeightDistanceDTI,      100*All{2}.NormalSpreadWeightDistanceDTI     /All{2}.TotalNormal, All{3}.NormalSpreadWeightDistanceDTI,      100*All{3}.NormalSpreadWeightDistanceDTI     /All{3}.TotalNormal, All{4}.NormalSpreadWeightDistanceDTI,      100*All{4}.NormalSpreadWeightDistanceDTI     /All{4}.TotalNormal);
fprintf('Weight Distance DCM:     %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightDistanceDCM,      100*All{1}.NormalSpreadWeightDistanceDCM     /All{1}.TotalNormal, All{2}.NormalSpreadWeightDistanceDCM,      100*All{2}.NormalSpreadWeightDistanceDCM     /All{2}.TotalNormal, All{3}.NormalSpreadWeightDistanceDCM,      100*All{3}.NormalSpreadWeightDistanceDCM     /All{3}.TotalNormal, All{4}.NormalSpreadWeightDistanceDCM,      100*All{4}.NormalSpreadWeightDistanceDCM     /All{4}.TotalNormal);
fprintf('Frequency FMRI:          %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightFreqFMRI,         100*All{1}.NormalSpreadWeightFreqFMRI        /All{1}.TotalNormal, All{2}.NormalSpreadWeightFreqFMRI,         100*All{2}.NormalSpreadWeightFreqFMRI        /All{2}.TotalNormal, All{3}.NormalSpreadWeightFreqFMRI,         100*All{3}.NormalSpreadWeightFreqFMRI        /All{3}.TotalNormal, All{4}.NormalSpreadWeightFreqFMRI,         100*All{4}.NormalSpreadWeightFreqFMRI        /All{4}.TotalNormal);
fprintf('Frequency DTI:           %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightFreqDTI,          100*All{1}.NormalSpreadWeightFreqDTI         /All{1}.TotalNormal, All{2}.NormalSpreadWeightFreqDTI,          100*All{2}.NormalSpreadWeightFreqDTI         /All{2}.TotalNormal, All{3}.NormalSpreadWeightFreqDTI,          100*All{3}.NormalSpreadWeightFreqDTI         /All{3}.TotalNormal, All{4}.NormalSpreadWeightFreqDTI,          100*All{4}.NormalSpreadWeightFreqDTI         /All{4}.TotalNormal);
fprintf('Frequency DCM:           %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightFreqDCM,          100*All{1}.NormalSpreadWeightFreqDCM         /All{1}.TotalNormal, All{2}.NormalSpreadWeightFreqDCM,          100*All{2}.NormalSpreadWeightFreqDCM         /All{2}.TotalNormal, All{3}.NormalSpreadWeightFreqDCM,          100*All{3}.NormalSpreadWeightFreqDCM         /All{3}.TotalNormal, All{4}.NormalSpreadWeightFreqDCM,          100*All{4}.NormalSpreadWeightFreqDCM         /All{4}.TotalNormal);
fprintf('Frequency Distance FMRI: %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightDistanceFreqFMRI, 100*All{1}.NormalSpreadWeightDistanceFreqFMRI/All{1}.TotalNormal, All{2}.NormalSpreadWeightDistanceFreqFMRI, 100*All{2}.NormalSpreadWeightDistanceFreqFMRI/All{2}.TotalNormal, All{3}.NormalSpreadWeightDistanceFreqFMRI, 100*All{3}.NormalSpreadWeightDistanceFreqFMRI/All{3}.TotalNormal, All{4}.NormalSpreadWeightDistanceFreqFMRI, 100*All{4}.NormalSpreadWeightDistanceFreqFMRI/All{4}.TotalNormal);
fprintf('Frequency Distance DTI:  %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightDistanceFreqDTI,  100*All{1}.NormalSpreadWeightDistanceFreqDTI /All{1}.TotalNormal, All{2}.NormalSpreadWeightDistanceFreqDTI,  100*All{2}.NormalSpreadWeightDistanceFreqDTI /All{2}.TotalNormal, All{3}.NormalSpreadWeightDistanceFreqDTI,  100*All{3}.NormalSpreadWeightDistanceFreqDTI /All{3}.TotalNormal, All{4}.NormalSpreadWeightDistanceFreqDTI,  100*All{4}.NormalSpreadWeightDistanceFreqDTI /All{4}.TotalNormal);
fprintf('Frequency Distance DCM:  %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.NormalSpreadWeightDistanceFreqDCM,  100*All{1}.NormalSpreadWeightDistanceFreqDCM /All{1}.TotalNormal, All{2}.NormalSpreadWeightDistanceFreqDCM,  100*All{2}.NormalSpreadWeightDistanceFreqDCM /All{2}.TotalNormal, All{3}.NormalSpreadWeightDistanceFreqDCM,  100*All{3}.NormalSpreadWeightDistanceFreqDCM /All{3}.TotalNormal, All{4}.NormalSpreadWeightDistanceFreqDCM,  100*All{4}.NormalSpreadWeightDistanceFreqDCM /All{4}.TotalNormal);
fprintf('\n');

fprintf('Pathogenic protein spread\n');
fprintf('                          AD quantity           %% | C9orf72 quantity           %% | GRN quantity           %% | MAPT quantity           %%\n');
fprintf('Extracellular diffusion: %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadExtracellular,          100*All{1}.PathogenicSpreadExtracellular         /All{1}.TotalPathogenic, All{2}.PathogenicSpreadExtracellular,          100*All{2}.PathogenicSpreadExtracellular         /All{2}.TotalPathogenic, All{3}.PathogenicSpreadExtracellular,          100*All{3}.PathogenicSpreadExtracellular         /All{3}.TotalPathogenic, All{4}.PathogenicSpreadExtracellular,          100*All{4}.PathogenicSpreadExtracellular         /All{4}.TotalPathogenic);
fprintf('Weight FMRI:             %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightFMRI,             100*All{1}.PathogenicSpreadWeightFMRI            /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightFMRI,             100*All{2}.PathogenicSpreadWeightFMRI            /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightFMRI,             100*All{3}.PathogenicSpreadWeightFMRI            /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightFMRI,             100*All{4}.PathogenicSpreadWeightFMRI            /All{4}.TotalPathogenic);
fprintf('Weight DTI:              %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightDTI,              100*All{1}.PathogenicSpreadWeightDTI             /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightDTI,              100*All{2}.PathogenicSpreadWeightDTI             /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightDTI,              100*All{3}.PathogenicSpreadWeightDTI             /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightDTI,              100*All{4}.PathogenicSpreadWeightDTI             /All{4}.TotalPathogenic);
fprintf('Weight DCM:              %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightDCM,              100*All{1}.PathogenicSpreadWeightDCM             /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightDCM,              100*All{2}.PathogenicSpreadWeightDCM             /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightDCM,              100*All{3}.PathogenicSpreadWeightDCM             /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightDCM,              100*All{4}.PathogenicSpreadWeightDCM             /All{4}.TotalPathogenic);
fprintf('Weight Distance FMRI:    %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightDistanceFMRI,     100*All{1}.PathogenicSpreadWeightDistanceFMRI    /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightDistanceFMRI,     100*All{2}.PathogenicSpreadWeightDistanceFMRI    /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightDistanceFMRI,     100*All{3}.PathogenicSpreadWeightDistanceFMRI    /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightDistanceFMRI,     100*All{4}.PathogenicSpreadWeightDistanceFMRI    /All{4}.TotalPathogenic);
fprintf('Weight Distance DTI:     %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightDistanceDTI,      100*All{1}.PathogenicSpreadWeightDistanceDTI     /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightDistanceDTI,      100*All{2}.PathogenicSpreadWeightDistanceDTI     /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightDistanceDTI,      100*All{3}.PathogenicSpreadWeightDistanceDTI     /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightDistanceDTI,      100*All{4}.PathogenicSpreadWeightDistanceDTI     /All{4}.TotalPathogenic);
fprintf('Weight Distance DCM:     %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightDistanceDCM,      100*All{1}.PathogenicSpreadWeightDistanceDCM     /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightDistanceDCM,      100*All{2}.PathogenicSpreadWeightDistanceDCM     /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightDistanceDCM,      100*All{3}.PathogenicSpreadWeightDistanceDCM     /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightDistanceDCM,      100*All{4}.PathogenicSpreadWeightDistanceDCM     /All{4}.TotalPathogenic);
fprintf('Frequency FMRI:          %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightFreqFMRI,         100*All{1}.PathogenicSpreadWeightFreqFMRI        /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightFreqFMRI,         100*All{2}.PathogenicSpreadWeightFreqFMRI        /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightFreqFMRI,         100*All{3}.PathogenicSpreadWeightFreqFMRI        /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightFreqFMRI,         100*All{4}.PathogenicSpreadWeightFreqFMRI        /All{4}.TotalPathogenic);
fprintf('Frequency DTI:           %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightFreqDTI,          100*All{1}.PathogenicSpreadWeightFreqDTI         /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightFreqDTI,          100*All{2}.PathogenicSpreadWeightFreqDTI         /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightFreqDTI,          100*All{3}.PathogenicSpreadWeightFreqDTI         /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightFreqDTI,          100*All{4}.PathogenicSpreadWeightFreqDTI         /All{4}.TotalPathogenic);
fprintf('Frequency DCM:           %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightFreqDCM,          100*All{1}.PathogenicSpreadWeightFreqDCM         /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightFreqDCM,          100*All{2}.PathogenicSpreadWeightFreqDCM         /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightFreqDCM,          100*All{3}.PathogenicSpreadWeightFreqDCM         /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightFreqDCM,          100*All{4}.PathogenicSpreadWeightFreqDCM         /All{4}.TotalPathogenic);
fprintf('Frequency Distance FMRI: %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightDistanceFreqFMRI, 100*All{1}.PathogenicSpreadWeightDistanceFreqFMRI/All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightDistanceFreqFMRI, 100*All{2}.PathogenicSpreadWeightDistanceFreqFMRI/All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightDistanceFreqFMRI, 100*All{3}.PathogenicSpreadWeightDistanceFreqFMRI/All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightDistanceFreqFMRI, 100*All{4}.PathogenicSpreadWeightDistanceFreqFMRI/All{4}.TotalPathogenic);
fprintf('Frequency Distance DTI:  %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightDistanceFreqDTI,  100*All{1}.PathogenicSpreadWeightDistanceFreqDTI /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightDistanceFreqDTI,  100*All{2}.PathogenicSpreadWeightDistanceFreqDTI /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightDistanceFreqDTI,  100*All{3}.PathogenicSpreadWeightDistanceFreqDTI /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightDistanceFreqDTI,  100*All{4}.PathogenicSpreadWeightDistanceFreqDTI /All{4}.TotalPathogenic);
fprintf('Frequency Distance DCM:  %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.PathogenicSpreadWeightDistanceFreqDCM,  100*All{1}.PathogenicSpreadWeightDistanceFreqDCM /All{1}.TotalPathogenic, All{2}.PathogenicSpreadWeightDistanceFreqDCM,  100*All{2}.PathogenicSpreadWeightDistanceFreqDCM /All{2}.TotalPathogenic, All{3}.PathogenicSpreadWeightDistanceFreqDCM,  100*All{3}.PathogenicSpreadWeightDistanceFreqDCM /All{3}.TotalPathogenic, All{4}.PathogenicSpreadWeightDistanceFreqDCM,  100*All{4}.PathogenicSpreadWeightDistanceFreqDCM /All{4}.TotalPathogenic);
fprintf('\n');

fprintf('Total protein spread\n');
fprintf('                          AD quantity           %% | C9orf72 quantity           %% | GRN quantity           %% | MAPT quantity           %%\n');
fprintf('Extracellular diffusion: %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadExtracellular,          100*All{1}.TotalSpreadExtracellular         /All{1}.TotalProtein, All{2}.TotalSpreadExtracellular,          100*All{2}.TotalSpreadExtracellular         /All{2}.TotalProtein, All{3}.TotalSpreadExtracellular,          100*All{3}.TotalSpreadExtracellular         /All{3}.TotalProtein, All{4}.TotalSpreadExtracellular,          100*All{4}.TotalSpreadExtracellular         /All{4}.TotalProtein);
fprintf('Weight FMRI:             %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightFMRI,             100*All{1}.TotalSpreadWeightFMRI            /All{1}.TotalProtein, All{2}.TotalSpreadWeightFMRI,             100*All{2}.TotalSpreadWeightFMRI            /All{2}.TotalProtein, All{3}.TotalSpreadWeightFMRI,             100*All{3}.TotalSpreadWeightFMRI            /All{3}.TotalProtein, All{4}.TotalSpreadWeightFMRI,             100*All{4}.TotalSpreadWeightFMRI            /All{4}.TotalProtein);
fprintf('Weight DTI:              %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightDTI,              100*All{1}.TotalSpreadWeightDTI             /All{1}.TotalProtein, All{2}.TotalSpreadWeightDTI,              100*All{2}.TotalSpreadWeightDTI             /All{2}.TotalProtein, All{3}.TotalSpreadWeightDTI,              100*All{3}.TotalSpreadWeightDTI             /All{3}.TotalProtein, All{4}.TotalSpreadWeightDTI,              100*All{4}.TotalSpreadWeightDTI             /All{4}.TotalProtein);
fprintf('Weight DCM:              %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightDCM,              100*All{1}.TotalSpreadWeightDCM             /All{1}.TotalProtein, All{2}.TotalSpreadWeightDCM,              100*All{2}.TotalSpreadWeightDCM             /All{2}.TotalProtein, All{3}.TotalSpreadWeightDCM,              100*All{3}.TotalSpreadWeightDCM             /All{3}.TotalProtein, All{4}.TotalSpreadWeightDCM,              100*All{4}.TotalSpreadWeightDCM             /All{4}.TotalProtein);
fprintf('Weight Distance FMRI:    %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightDistanceFMRI,     100*All{1}.TotalSpreadWeightDistanceFMRI    /All{1}.TotalProtein, All{2}.TotalSpreadWeightDistanceFMRI,     100*All{2}.TotalSpreadWeightDistanceFMRI    /All{2}.TotalProtein, All{3}.TotalSpreadWeightDistanceFMRI,     100*All{3}.TotalSpreadWeightDistanceFMRI    /All{3}.TotalProtein, All{4}.TotalSpreadWeightDistanceFMRI,     100*All{4}.TotalSpreadWeightDistanceFMRI    /All{4}.TotalProtein);
fprintf('Weight Distance DTI:     %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightDistanceDTI,      100*All{1}.TotalSpreadWeightDistanceDTI     /All{1}.TotalProtein, All{2}.TotalSpreadWeightDistanceDTI,      100*All{2}.TotalSpreadWeightDistanceDTI     /All{2}.TotalProtein, All{3}.TotalSpreadWeightDistanceDTI,      100*All{3}.TotalSpreadWeightDistanceDTI     /All{3}.TotalProtein, All{4}.TotalSpreadWeightDistanceDTI,      100*All{4}.TotalSpreadWeightDistanceDTI     /All{4}.TotalProtein);
fprintf('Weight Distance DCM:     %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightDistanceDCM,      100*All{1}.TotalSpreadWeightDistanceDCM     /All{1}.TotalProtein, All{2}.TotalSpreadWeightDistanceDCM,      100*All{2}.TotalSpreadWeightDistanceDCM     /All{2}.TotalProtein, All{3}.TotalSpreadWeightDistanceDCM,      100*All{3}.TotalSpreadWeightDistanceDCM     /All{3}.TotalProtein, All{4}.TotalSpreadWeightDistanceDCM,      100*All{4}.TotalSpreadWeightDistanceDCM     /All{4}.TotalProtein);
fprintf('Frequency FMRI:          %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightFreqFMRI,         100*All{1}.TotalSpreadWeightFreqFMRI        /All{1}.TotalProtein, All{2}.TotalSpreadWeightFreqFMRI,         100*All{2}.TotalSpreadWeightFreqFMRI        /All{2}.TotalProtein, All{3}.TotalSpreadWeightFreqFMRI,         100*All{3}.TotalSpreadWeightFreqFMRI        /All{3}.TotalProtein, All{4}.TotalSpreadWeightFreqFMRI,         100*All{4}.TotalSpreadWeightFreqFMRI        /All{4}.TotalProtein);
fprintf('Frequency DTI:           %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightFreqDTI,          100*All{1}.TotalSpreadWeightFreqDTI         /All{1}.TotalProtein, All{2}.TotalSpreadWeightFreqDTI,          100*All{2}.TotalSpreadWeightFreqDTI         /All{2}.TotalProtein, All{3}.TotalSpreadWeightFreqDTI,          100*All{3}.TotalSpreadWeightFreqDTI         /All{3}.TotalProtein, All{4}.TotalSpreadWeightFreqDTI,          100*All{4}.TotalSpreadWeightFreqDTI         /All{4}.TotalProtein);
fprintf('Frequency DCM:           %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightFreqDCM,          100*All{1}.TotalSpreadWeightFreqDCM         /All{1}.TotalProtein, All{2}.TotalSpreadWeightFreqDCM,          100*All{2}.TotalSpreadWeightFreqDCM         /All{2}.TotalProtein, All{3}.TotalSpreadWeightFreqDCM,          100*All{3}.TotalSpreadWeightFreqDCM         /All{3}.TotalProtein, All{4}.TotalSpreadWeightFreqDCM,          100*All{4}.TotalSpreadWeightFreqDCM         /All{4}.TotalProtein);
fprintf('Frequency Distance FMRI: %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightDistanceFreqFMRI, 100*All{1}.TotalSpreadWeightDistanceFreqFMRI/All{1}.TotalProtein, All{2}.TotalSpreadWeightDistanceFreqFMRI, 100*All{2}.TotalSpreadWeightDistanceFreqFMRI/All{2}.TotalProtein, All{3}.TotalSpreadWeightDistanceFreqFMRI, 100*All{3}.TotalSpreadWeightDistanceFreqFMRI/All{3}.TotalProtein, All{4}.TotalSpreadWeightDistanceFreqFMRI, 100*All{4}.TotalSpreadWeightDistanceFreqFMRI/All{4}.TotalProtein);
fprintf('Frequency Distance DTI:  %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightDistanceFreqDTI,  100*All{1}.TotalSpreadWeightDistanceFreqDTI /All{1}.TotalProtein, All{2}.TotalSpreadWeightDistanceFreqDTI,  100*All{2}.TotalSpreadWeightDistanceFreqDTI /All{2}.TotalProtein, All{3}.TotalSpreadWeightDistanceFreqDTI,  100*All{3}.TotalSpreadWeightDistanceFreqDTI /All{3}.TotalProtein, All{4}.TotalSpreadWeightDistanceFreqDTI,  100*All{4}.TotalSpreadWeightDistanceFreqDTI /All{4}.TotalProtein);
fprintf('Frequency Distance DCM:  %12.3f  %10.6f       %12.3f  %10.6f   %12.3f  %10.6f    %12.3f  %10.6f\n', All{1}.TotalSpreadWeightDistanceFreqDCM,  100*All{1}.TotalSpreadWeightDistanceFreqDCM /All{1}.TotalProtein, All{2}.TotalSpreadWeightDistanceFreqDCM,  100*All{2}.TotalSpreadWeightDistanceFreqDCM /All{2}.TotalProtein, All{3}.TotalSpreadWeightDistanceFreqDCM,  100*All{3}.TotalSpreadWeightDistanceFreqDCM /All{3}.TotalProtein, All{4}.TotalSpreadWeightDistanceFreqDCM,  100*All{4}.TotalSpreadWeightDistanceFreqDCM /All{4}.TotalProtein);
fprintf('\n');

fprintf('\n                                                            Abnormality timings\n      AD                          |       C9orf72                      |      GRN                         |       MAPT\n');
fprintf('----------------------------------------------------------------------------------------------------------------------------------------\n');
for i = 1:numel(All{1}.AbnormalityTimingsOrdered)
    fprintf('%5d %s',All{1}.AbnormalityTimingsOrdered(i), All{1}.AbnormalityOrderedNames{i});
    for j = 1:30-numel(All{1}.AbnormalityOrderedNames{i})
        fprintf(' ');
    end
    fprintf('%5d %s',All{2}.AbnormalityTimingsOrdered(i), All{2}.AbnormalityOrderedNames{i});
    for j = 1:30-numel(All{2}.AbnormalityOrderedNames{i})
        fprintf(' ');
    end
    fprintf('%5d %s',All{3}.AbnormalityTimingsOrdered(i), All{3}.AbnormalityOrderedNames{i});
    for j = 1:30-numel(All{3}.AbnormalityOrderedNames{i})
        fprintf(' ');
    end
    fprintf('%5d %s\n',All{4}.AbnormalityTimingsOrdered(i), All{4}.AbnormalityOrderedNames{i});
end

end



