function AllParams = WholeBrainInitializationResults(ParameterSetFilename)
AllParams.start_path = pwd;
addpath(genpath(AllParams.start_path));
addpath(genpath('/SAN/medic/nexopathy/MATLAB/'));
addpath(genpath('/SAN/medic/nexopathy/kool/MATLAB/'));
dispstat('','init');
dlmwrite('Finished.dat',0,' ');
dlmwrite('Started.dat',0,' ');

load(ParameterSetFilename, 'bestmodel');
AllParams.ParameterSet = bestmodel;

AllParams.QuickSimulationEnd = false;
AllParams.ImageNumbers = [6 7 11 13 15 16 20 23 24 26];
AllParams.NiftyregProcessing = false;
AllParams.PerformSmoothing = false;
AllParams.GenerateCSFandWMparcellations = false;
AllParams.BOLDUseSmoothedImage = true;
AllParams.BOLDDemean = true;
AllParams.BOLDNormalize = true;
AllParams.ComputeBOLD = false;
AllParams.SynapticUseSmoothedImage = true;
AllParams.ComputeSynapticSignals = false;
AllParams.DTISmallConnectionsEmphasized = true;
AllParams.DoDCMpreprocessing = false;
AllParams.TractographyPrior = true;
AllParams.TractographyPriorValues = [4 12 1];
% aprior = 4;
% bprior = 12;
% Soprior = 1;
% if(sum(DTInorm(:))> 1e-10)
%     pC.A = Soprior./(1+Soprior*exp(aprior-bprior*DTInorm));
% end
AllParams.TractographyPriorSmall = true;
AllParams.ComputeDCM = false;
AllParams.SkipDCM = false;
AllParams.EBMorAllnodes   = 1;   % 1 - 27 nodes EBM, 2 - 57 nodes

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Paramaters to load from file
%Model Parameters
AllParams.WhichDisease    = 1;   % 1 - Alzheimer's, 2 - C9orf72, 3 - GRN, 4 - MAPT
AllParams.ProteinType     = 1;   % 1 2 3 4
AllParams.Metric          = 1;   % 1 2 3 4
AllParams.ProteinLocation = 1;   % 1 - Hippocampus, 2 - Parahippocampal gyrus, 3 - Entorhinal cortex

AllParams.FMRIspread      = 1; % 0 - no, 1 yes
AllParams.DTIspread       = 1; % 0 - no, 1 small emphasized, 2 - large emphasized
AllParams.DCMspread       = 1; % 0 - no, 1 - fmri, 2 - fmri + small, 3 - fmri + large
AllParams.NEURONEffect    = 1; % 1 - damage lowers firing frequencies. 2 - damage increases firing frequencies
AllParams.ChosenOptimization = 1;

%
AllParams.WhichDisease       = AllParams.ParameterSet(1); % 1 - Alzheimer's, 2 - C9orf72, 3 - GRN, 4 - MAPT
AllParams.ProteinType        = AllParams.ParameterSet(2); % 1 2 3 4
AllParams.Metric             = AllParams.ParameterSet(3); % 1 2 3 4
AllParams.ProteinLocation    = AllParams.ParameterSet(4); % 1 - Hippocampus, 2 - Parahippocampal gyrus, 3 - Entorhinal cortex

AllParams.FMRIspread         = AllParams.ParameterSet(5); % 0 - no, 1 yes
AllParams.DTIspread          = AllParams.ParameterSet(6); % 0 - no, 1 small, 2 - large
AllParams.DCMspread          = AllParams.ParameterSet(7); % 0 - no, 1 - fmri, 2 - fmri + small, 3 - fmri + large
AllParams.NEURONEffect       = AllParams.ParameterSet(8); % 1 - damage lowers firing frequencies. 2 - damage increases firing frequencies
AllParams.ChosenOptimization = AllParams.ParameterSet(9); % 1 - General Search, 2 - Cuckoo

% Optimisation parameters. These will be their starting values during
% optimisation
AllParams.Seedsize                                   = AllParams.ParameterSet(11);
AllParams.ExtracellularDiffusionFraction             = AllParams.ParameterSet(12);
AllParams.ExtracellularDiffusionSpeed                = AllParams.ParameterSet(13);
AllParams.NetworkDiffusionWeightFractionFMRI         = AllParams.ParameterSet(14);
AllParams.NetworkDiffusionWeightFractionDTI          = AllParams.ParameterSet(15);
AllParams.NetworkDiffusionWeightFractionDCM          = AllParams.ParameterSet(16);
AllParams.NetworkDiffusionWeightDistanceFractionFMRI = AllParams.ParameterSet(17);
AllParams.NetworkDiffusionWeightDistanceFractionDTI  = AllParams.ParameterSet(18);
AllParams.NetworkDiffusionWeightDistanceFractionDCM  = AllParams.ParameterSet(19);
AllParams.SynapticTransferWeightFractionFMRI         = AllParams.ParameterSet(20);
AllParams.SynapticTransferWeightFractionDTI          = AllParams.ParameterSet(21);
AllParams.SynapticTransferWeightFractionDCM          = AllParams.ParameterSet(22);
AllParams.SynapticTransferWeightDistanceFractionFMRI = AllParams.ParameterSet(23);
AllParams.SynapticTransferWeightDistanceFractionDTI  = AllParams.ParameterSet(24);
AllParams.SynapticTransferWeightDistanceFractionDCM  = AllParams.ParameterSet(25);
AllParams.NetworkDiffusionSpeed                      = AllParams.ParameterSet(26);
AllParams.NEURONMisfold                              = AllParams.ParameterSet(27);
AllParams.NEURONDiffusionSpeed                       = AllParams.ParameterSet(28);
AllParams.NEURONDiffusion                            = AllParams.ParameterSet(29);
AllParams.NEURONTransport                            = AllParams.ParameterSet(30);
AllParams.NEURONSynaptic                             = AllParams.ParameterSet(31);
AllParams.NEURONDamage                               = AllParams.ParameterSet(32);


AllParams.NetworkDiffusionWeightFractionFMRI         = 0;
AllParams.NetworkDiffusionWeightDistanceFractionFMRI = 0;
AllParams.SynapticTransferWeightFractionFMRI         = 0;
AllParams.SynapticTransferWeightFractionDTI          = 0;
AllParams.SynapticTransferWeightFractionDCM          = 0;
AllParams.SynapticTransferWeightDistanceFractionFMRI = 0;
AllParams.SynapticTransferWeightDistanceFractionDTI  = 0;
AllParams.SynapticTransferWeightDistanceFractionDCM  = 0;

%Other parameters
AllParams.Verbose                               = true;
AllParams.NumTimesteps                          = 1000000;
AllParams.InitialConcentrationNormalAll         = 0.01;
AllParams.InitialConcentrationPathogenicAll     = 0.00;

if(AllParams.WhichDisease == 1)

    
    
    AllParams.DiseaseName = 'AD';
    AllParams.DiseaseEpicentres = cell(1,1);
    AllParams.DiseaseEpicentres{1} = 'Anterior Cingulate';
    AllParams.DiseaseEpicentres{2} = 'Hippocampus';
    AllParams.DiseaseEpicentres{3} = 'Amygdala';
    
    AllParams.DiseaseNumRegions = 27;
    AllParams.DiseaseGroundTruthSequence = [131 132; ...
        48 49; ...
        32 33; ...
        113 114; ...
        115 116; ...
        137 138; ...
        139 140; ...
        123 124; ...
        135 136; ...
        127 128; ...
        129 130; ...
        121 122; ...
        101 102; ...
        103 104; ...
        60 61; ...
        109 110; ...
        105 106; ...
        133 134; ...
        24 31; ...
        119 120; ...
        58 59; ...
        125 126; ...
        111 112; ...
        37 38; ...
        107 108; ...
        56 57; ...
        117 118];
    
    
elseif(AllParams.WhichDisease == 2)
   
    
    
    AllParams.DiseaseName = 'C9orf72';
    AllParams.DiseaseEpicentres = cell(1,1);
    AllParams.DiseaseEpicentres{1} = 'Supratemporal';
    AllParams.DiseaseEpicentres{2} = 'Thalamus Proper';
    AllParams.DiseaseEpicentres{3} = 'Putamen';
    
    %     {'10.  Supra Temp '      }
    %     {'Thalamus Proper'       }
    %     {'Putamen'               }
    %     {'Pallidum'              }
    %     {'20.  Post Insula '     }
    %     {'19.  Ant Insula  '     }
    %     {'2.  DLPFC '            }
    %     {'4.  Motor '            }
    %     {'5.  Opercular '        }
    %     {'3.  VMPFC '            }
    %     {'1  Orbitofrontal '     }
    %     {'16.  Anterior Cing '   }
    %     {'8.  Lateral Temp  '    }
    %     {'12.  Lateral Parietal '}
    %     {'Hippocampus'           }
    %     {'Amygdala'              }
    %     {'11.  Medial Parietal ' }
    %     {'18.  Posterior Cing '  }
    %     {'Caudate'               }
    %     {'Pons'                  }
    %     {'13.  Sensory '         }
    %     {'7.  Medial Temp '      }
    %     {'9.  Temporal Pole '    }
    %     {'14.  Medial occ '      }
    %     {'15.  Lateral Occ '     }
    %     {'6.  FRP '              }
    %     {'Accumbens Area'        }
    %     {'17.  Middle Cing '     }
    %     {'Brain Stem'            }
    
    
    AllParams.DiseaseNumRegions = 27;
    AllParams.DiseaseGroundTruthSequence = [119 120; ...
        60 61; ...
        58 59; ...
        56 57; ...
        137 138; ...
        139 140; ...
        103 104; ...
        107 108; ...
        109 110; ...
        105 106; ...
        101 102; ...
        131 132; ...
        115 116; ...
        123 124; ...
        48 49; ...
        32 33; ...
        121 122; ...
        135 136; ...
        37 38; ...
        125 126; ...
        113 114; ...
        117 118; ...
        127 128; ...
        133 134; ...
        129 130; ...
        111 112; ...
        24 31];
    
elseif(AllParams.WhichDisease == 3)
    
    
    AllParams.DiseaseName = 'GRN';
    AllParams.DiseaseEpicentres = cell(1,1);
    AllParams.DiseaseEpicentres{1} = 'Middle Cingulate';
    AllParams.DiseaseEpicentres{2} = 'Lateral Parietal';
    AllParams.DiseaseEpicentres{3} = 'Medial Parietal';
    
    %     {'17.  Middle Cing '     }
    %     {'12.  Lateral Parietal '}
    %     {'11.  Medial Parietal ' }
    %     {'16.  Anterior Cing '   }
    %     {'Pallidum'              }
    %     {'Putamen'               }
    %     {'4.  Motor '            }
    %     {'2.  DLPFC '            }
    %     {'5.  Opercular '        }
    %     {'19.  Ant Insula  '     }
    %     {'20.  Post Insula '     }
    %     {'3.  VMPFC '            }
    %     {'Caudate'               }
    %     {'1  Orbitofrontal '     }
    %     {'8.  Lateral Temp  '    }
    %     {'10.  Supra Temp '      }
    %     {'Hippocampus'           }
    %     {'18.  Posterior Cing '  }
    %     {'9.  Temporal Pole '    }
    %     {'7.  Medial Temp '      }
    %     {'Amygdala'              }
    %     {'Brain Stem'            }
    %     {'Pons'                  }
    %     {'Thalamus Proper'       }
    %     {'13.  Sensory '         }
    %     {'Accumbens Area'        }
    %     {'15.  Lateral Occ '     }
    %     {'6.  FRP '              }
    %     {'14.  Medial occ '      }
    
    AllParams.DiseaseNumRegions = 27;
    AllParams.DiseaseGroundTruthSequence = [133 134; ...
        123 124; ...
        121 122; ...
        131 132; ...
        56 57; ...
        58 59; ...
        107 108; ...
        103 104; ...
        109 110; ...
        137 138; ...
        139 140; ...
        105 106; ...
        37 38; ...
        101 102; ...
        115 116; ...
        119 120; ...
        48 49; ...
        135 136; ...
        117 118; ...
        113 114; ...
        32 33; ...
        60 61; ...
        125 126; ...
        24 31; ...
        129 130; ...
        111 112; ...
        127 128];
    
    
elseif(AllParams.WhichDisease == 4)
   
    
    AllParams.DiseaseName = 'MAPT';
    AllParams.DiseaseEpicentres = cell(1,1);
    AllParams.DiseaseEpicentres{1} = 'Accumbens Area';
    AllParams.DiseaseEpicentres{2} = 'Supratemporal';
    AllParams.DiseaseEpicentres{3} = 'Temporal Pole';
    
    %     {'Accumbens Area'        }
    %     {'10.  Supra Temp '      }
    %     {'9.  Temporal Pole '    }
    %     {'Amygdala'              }
    %     {'Hippocampus'           }
    %     {'7.  Medial Temp '      }
    %     {'20.  Post Insula '     }
    %     {'Pallidum'              }
    %     {'Putamen'               }
    %     {'19.  Ant Insula  '     }
    %     {'8.  Lateral Temp  '    }
    %     {'3.  VMPFC '            }
    %     {'1  Orbitofrontal '     }
    %     {'16.  Anterior Cing '   }
    %     {'2.  DLPFC '            }
    %     {'5.  Opercular '        }
    %     {'12.  Lateral Parietal '}
    %     {'Caudate'               }
    %     {'6.  FRP '              }
    %     {'15.  Lateral Occ '     }
    %     {'13.  Sensory '         }
    %     {'14.  Medial occ '      }
    %     {'11.  Medial Parietal ' }
    %     {'4.  Motor '            }
    %     {'17.  Middle Cing '     }
    %     {'18.  Posterior Cing '  }
    %     {'Pons'                  }
    %     {'Thalamus Proper'       }
    %     {'Brain Stem'            }
    
    AllParams.DiseaseNumRegions = 27;
    AllParams.DiseaseGroundTruthSequence = [24 31; ...
        119 120; ...
        117 118; ...
        113 114; ...
        32 33; ...
        48 49; ...
        139 140; ...
        137 138; ...
        58 59; ...
        56 57; ...
        115 116; ...
        105 106; ...
        101 102; ...
        131 132; ...
        109 110; ...
        103 104; ...
        123 124; ...
        37 38; ...
        111 112; ...
        129 130; ...
        125 126; ...
        127 128; ...
        121 122; ...
        107 108; ...
        133 134; ...
        135 136; ...
        60 61];
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


if(AllParams.FMRIspread == 0)
    AllParams.noFMRI = true;
end

if(AllParams.DTIspread == 0)
    AllParams.noDTI = true;
elseif(AllParams.DTIspread == 1)
    AllParams.DTISmallConnectionsEmphasized = true;
elseif(AllParams.DTIspread == 2)
    AllParams.DTISmallConnectionsEmphasized = false;
end

AllParams.SkipDCM = false;
if(AllParams.DCMspread == 0)
    AllParams.SkipDCM = true;
    AllParams.noDCM = true;
elseif(AllParams.DCMspread == 1)
    AllParams.TractographyPrior = false;
elseif(AllParams.DCMspread == 2)
    AllParams.TractographyPrior = true;
    AllParams.TractographyPriorSmall = true;
elseif(AllParams.DCMspread == 3)
    AllParams.TractographyPrior = true;
    AllParams.TractographyPriorSmall = false;
end



%% Process stuff 2
if(AllParams.start_path(2) == 'S')
    AllParams.MACorCluster = 2; %0 - MAC, 1 - PC,  2 - Cluster. This determines where to save/load from.
elseif(AllParams.start_path(1) == 'C' || AllParams.start_path(1) == 'D')
    AllParams.MACorCluster = 1; %0 - MAC, 1 - PC,  2 - Cluster. This determines where to save/load from.
else
    AllParams.MACorCluster = 0; %0 - MAC, 1 - PC,  2 - Cluster. This determines where to save/load from.
end


if(AllParams.MACorCluster == 0)
    AllParams.save_path = '/Users/kgeorgiadi/Documents/PhD/Results/LastPaper/koolOld/';
    AllParams.NIFTYREG_INSTALL = '../../../GeneralCode/NiftyReg_Install';
    AllParams.dti_path = '/Users/kgeorgiadi/Documents/PhD/Data/FMRIDWIDATA/dti_output/';
    AllParams.fmri_path = '/Users/kgeorgiadi/Documents/PhD/Data/FMRIDWIDATA/fmri_output/';
    AllParams.parcellation_path = '/Users/kgeorgiadi/Documents/PhD/Data/FMRIDWIDATA/gif_output/';
elseif(AllParams.MACorCluster == 1)
    AllParams.save_path = 'D:\Data\PhD\Results\LastPaper\';
    AllParams.NIFTYREG_INSTALL = '..\..\..\GeneralCode\NiftyReg_Install';
    AllParams.dti_path = 'D:\Data\PhD\FMRIDWIDATA\dti_output\';
    AllParams.fmri_path = 'D:\Data\PhD\FMRIDWIDATA\fmri_output\';
    AllParams.parcellation_path = 'D:\Data\PhD\FMRIDWIDATA\gif_output\';
elseif(AllParams.MACorCluster == 2)
    AllParams.save_path = '/SAN/medic/nexopathy/kool/Results/';
    AllParams.NIFTYREG_INSTALL = '/share/apps/cmic/niftyreg_v1.5.43';
    AllParams.dti_path = '/SAN/medic/nexopathy/BrainScale/YOAD_dwi_rs/dti_output/';
    AllParams.fmri_path = '/SAN/medic/nexopathy/BrainScale/YOAD_dwi_rs/fmri_output/';
    AllParams.parcellation_path = '/SAN/medic/nexopathy/BrainScale/YOAD_dwi_rs/gif_output/';
end

if(exist(AllParams.save_path,'dir') == 0)
    mkdir(AllParams.save_path);
end

AllParams.MyInput = [AllParams.Seedsize; ...
    AllParams.ExtracellularDiffusionFraction; ...
    AllParams.ExtracellularDiffusionSpeed; ...
    AllParams.NetworkDiffusionWeightFractionFMRI; ...
    AllParams.NetworkDiffusionWeightFractionDTI; ...
    AllParams.NetworkDiffusionWeightFractionDCM; ...
    AllParams.NetworkDiffusionWeightDistanceFractionFMRI; ...
    AllParams.NetworkDiffusionWeightDistanceFractionDTI; ...
    AllParams.NetworkDiffusionWeightDistanceFractionDCM; ...
    AllParams.SynapticTransferWeightFractionFMRI; ...
    AllParams.SynapticTransferWeightFractionDTI; ...
    AllParams.SynapticTransferWeightFractionDCM; ...
    AllParams.SynapticTransferWeightDistanceFractionFMRI; ...
    AllParams.SynapticTransferWeightDistanceFractionDTI; ...
    AllParams.SynapticTransferWeightDistanceFractionDCM; ...
    AllParams.NetworkDiffusionSpeed; ...
    
    AllParams.NEURONMisfold; ...
    AllParams.NEURONDiffusionSpeed; ...
    AllParams.NEURONDiffusion; ...
    AllParams.NEURONTransport; ...
    AllParams.NEURONSynaptic; ...
    AllParams.NEURONDamage];

AllParams.InputScaling = [0.1; ...
    1; ...
    1; ...
    
    1; ...
    1; ...
    1; ...
    1; ...
    1; ...
    1; ...
    1; ...
    1; ...
    1; ...
    1; ...
    1; ...
    1; ...
    
    1; ...
    
    1; ...
    1000; ...
    1; ...
    1; ...
    1; ...
    0.1];

end

