function [TIV, GM, WM, CSF, DGM, BS, BAS, NvCSF, Names, Mapping, Volume, Active, Symmetry, Tissues] = WholeBrainLoadVolumeData(filename)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/kgeorgiadi/Documents/PhD/Temp/T1w/01-026-01-01-MR01_gif_volumes.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/02/09 17:38:33

%% Initialize variables.
delimiter = ',';
startRow = 2;

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Allocate imported array to column variable names
TIV = cell2mat(raw(:, 1));
GM = cell2mat(raw(:, 2));
WM = cell2mat(raw(:, 3));
CSF = cell2mat(raw(:, 4));
DGM = cell2mat(raw(:, 5));
BS = cell2mat(raw(:, 6));
BAS = cell2mat(raw(:, 7));
NvCSF = cell2mat(raw(:, 8));

%Tissue types: 0 non brain 1 CSF 2 GM 3 WM 4 Deep GM 5 Brain Stem
Names{1,1} = '3rd Ventricle';
Mapping(1,1) = 5;
Volume(1,1) = cell2mat(raw(:, 9));
Active(1,1) = 0;
Symmetry(1,1) = 0;
Tissues(1,1) = 1;

Names{2,1} = '4th Ventricle';
Mapping(2,1) = 12;
Volume(2,1) = cell2mat(raw(:, 10));
Active(2,1) = 0;
Symmetry(2,1) = 0;
Tissues(2,1) = 1;

Names{3,1} = 'Right Accumbens Area';
Mapping(3,1) = 24;
Volume(3,1) = cell2mat(raw(:, 11));
Active(3,1) = 1;
Symmetry(3,1) = 31;
Tissues(3,1) = 4;

Names{4,1} = 'Left Accumbens Area';
Mapping(4,1) = 31;
Volume(4,1) = cell2mat(raw(:, 12));
Active(4,1) = 1;
Symmetry(4,1) = 24;
Tissues(4,1) = 4;

Names{5,1} = 'Right Amygdala';
Mapping(5,1) = 32;
Volume(5,1) = cell2mat(raw(:, 13));
Active(5,1) = 1;
Symmetry(5,1) = 33;
Tissues(5,1) = 4;

Names{6,1} = 'Left Amygdala';
Mapping(6,1) = 33;
Volume(6,1) = cell2mat(raw(:, 14));
Active(6,1) = 1;
Symmetry(6,1) = 32;
Tissues(6,1) = 4;

Names{7,1} = 'Pons';
Mapping(7,1) = 35;
Volume(7,1) = cell2mat(raw(:, 15));
Active(7,1) = 0;
Symmetry(7,1) = 0;
Tissues(7,1) = 5;

Names{8,1} = 'Brain Stem';
Mapping(8,1) = 36;
Volume(8,1) = cell2mat(raw(:, 16));
Active(8,1) = 0;
Symmetry(8,1) = 0;
Tissues(8,1) = 5;

Names{9,1} = 'Right Caudate';
Mapping(9,1) = 37;
Volume(9,1) = cell2mat(raw(:, 17));
Active(9,1) = 1;
Symmetry(9,1) = 38;
Tissues(9,1) = 4;

Names{10,1} = 'Left Caudate';
Mapping(10,1) = 38;
Volume(10,1) = cell2mat(raw(:, 18));
Active(10,1) = 1;
Symmetry(10,1) = 37;
Tissues(10,1) = 4;

Names{11,1} = 'Right Cerebellum Exterior';
Mapping(11,1) = 39;
Volume(11,1) = cell2mat(raw(:, 19));
Active(11,1) = 0;
Symmetry(11,1) = 40;
Tissues(11,1) = 2;

Names{12,1} = 'Left Cerebellum Exterior';
Mapping(12,1) = 40;
Volume(12,1) = cell2mat(raw(:, 20));
Active(12,1) = 0;
Symmetry(12,1) = 39;
Tissues(12,1) = 2;

Names{13,1} = 'Right Cerebellum White Matter';
Mapping(13,1) = 41;
Volume(13,1) = cell2mat(raw(:, 21));
Active(13,1) = 0;
Symmetry(13,1) = 42;
Tissues(13,1) = 3;

Names{14,1} = 'Left Cerebellum White Matter';
Mapping(14,1) = 42;
Volume(14,1) = cell2mat(raw(:, 22));
Active(14,1) = 0;
Symmetry(14,1) = 41;
Tissues(14,1) = 3;

Names{15,1} = 'Right Cerebral White Matter';
Mapping(15,1) = 45;
Volume(15,1) = cell2mat(raw(:, 23));
Active(15,1) = 0;
Symmetry(15,1) = 46;
Tissues(15,1) = 3;

Names{16,1} = 'Left Cerebral White Matter';
Mapping(16,1) = 46;
Volume(16,1) = cell2mat(raw(:, 24));
Active(16,1) = 0;
Symmetry(16,1) = 45;
Tissues(16,1) = 3;

Names{17,1} = 'Right Hippocampus';
Mapping(17,1) = 48;
Volume(17,1) = cell2mat(raw(:, 25));
Active(17,1) = 1;
Symmetry(17,1) = 49;
Tissues(17,1) = 2;

Names{18,1} = 'Left Hippocampus';
Mapping(18,1) = 49;
Volume(18,1) = cell2mat(raw(:, 26));
Active(18,1) = 1;
Symmetry(18,1) = 48;
Tissues(18,1) = 2;

Names{19,1} = 'Right Inferior Lateral Ventricle';
Mapping(19,1) = 50;
Volume(19,1) = cell2mat(raw(:, 27));
Active(19,1) = 0;
Symmetry(19,1) = 51;
Tissues(19,1) = 1;

Names{20,1} = 'Left Inferior Lateral Ventricle';
Mapping(20,1) = 51;
Volume(20,1) = cell2mat(raw(:, 28));
Active(20,1) = 0;
Symmetry(20,1) = 50;
Tissues(20,1) = 1;

Names{21,1} = 'Right Lateral Ventricle';
Mapping(21,1) = 52;
Volume(21,1) = cell2mat(raw(:, 29));
Active(21,1) = 0;
Symmetry(21,1) = 53;
Tissues(21,1) = 1;

Names{22,1} = 'Left Lateral Ventricle';
Mapping(22,1) = 53;
Volume(22,1) = cell2mat(raw(:, 30));
Active(22,1) = 0;
Symmetry(22,1) = 52;
Tissues(22,1) = 1;

Names{23,1} = 'Right Pallidum';
Mapping(23,1) = 56;
Volume(23,1) = cell2mat(raw(:, 31));
Active(23,1) = 1;
Symmetry(23,1) = 57;
Tissues(23,1) = 4;

Names{24,1} = 'Left Pallidum';
Mapping(24,1) = 57;
Volume(24,1) = cell2mat(raw(:, 32));
Active(24,1) = 1;
Symmetry(24,1) = 56;
Tissues(24,1) = 4;

Names{25,1} = 'Right Putamen';
Mapping(25,1) = 58;
Volume(25,1) = cell2mat(raw(:, 33));
Active(25,1) = 1;
Symmetry(25,1) = 59;
Tissues(25,1) = 4;

Names{26,1} = 'Left Putamen';
Mapping(26,1) = 59;
Volume(26,1) = cell2mat(raw(:, 34));
Active(26,1) = 1;
Symmetry(26,1) = 58;
Tissues(26,1) = 4;

Names{27,1} = 'Right Thalamus Proper';
Mapping(27,1) = 60;
Volume(27,1) = cell2mat(raw(:, 35));
Active(27,1) = 1;
Symmetry(27,1) = 61;
Tissues(27,1) = 4;

Names{28,1} = 'Left Thalamus Proper';
Mapping(28,1) = 61;
Volume(28,1) = cell2mat(raw(:, 36));
Active(28,1) = 1;
Symmetry(28,1) = 60;
Tissues(28,1) = 4;

Names{29,1} = 'Right Ventral DC';
Mapping(29,1) = 62;
Volume(29,1) = cell2mat(raw(:, 37));
Active(29,1) = 0;
Symmetry(29,1) = 63;
Tissues(29,1) = 3;

Names{30,1} = 'Left Ventral DC';
Mapping(30,1) = 63;
Volume(30,1) = cell2mat(raw(:, 38));
Active(30,1) = 0;
Symmetry(30,1) = 62;
Tissues(30,1) = 3;

Names{31,1} = 'Cerebellar Vermal Lobules I-V';
Mapping(31,1) = 72;
Volume(31,1) = cell2mat(raw(:, 39));
Active(31,1) = 0;
Symmetry(31,1) = 0;
Tissues(31,1) = 2;

Names{32,1} = 'Cerebellar Vermal Lobules VI-VII';
Mapping(32,1) = 73;
Volume(32,1) = cell2mat(raw(:, 40));
Active(32,1) = 0;
Symmetry(32,1) = 0;
Tissues(32,1) = 2;

Names{33,1} = 'Cerebellar Vermal Lobules VIII-X';
Mapping(33,1) = 74;
Volume(33,1) = cell2mat(raw(:, 41));
Active(33,1) = 0;
Symmetry(33,1) = 0;
Tissues(33,1) = 2;

Names{34,1} = 'Left Basal Forebrain';
Mapping(34,1) = 76;
Volume(34,1) = cell2mat(raw(:, 42));
Active(34,1) = 1;
Symmetry(34,1) = 77;
Tissues(34,1) = 4;

Names{35,1} = 'Right Basal Forebrain';
Mapping(35,1) = 77;
Volume(35,1) = cell2mat(raw(:, 43));
Active(35,1) = 1;
Symmetry(35,1) = 76;
Tissues(35,1) = 4;

Names{36,1} = 'Right Anterior Cingulate Gyrus';
Mapping(36,1) = 101;
Volume(36,1) = cell2mat(raw(:, 44));
Active(36,1) = 1;
Symmetry(36,1) = 102;
Tissues(36,1) = 0;

Names{37,1} = 'Left Anterior Cingulate Gyrus';
Mapping(37,1) = 102;
Volume(37,1) = cell2mat(raw(:, 45));
Active(37,1) = 1;
Symmetry(37,1) = 101;
Tissues(37,1) = 2;

Names{38,1} = 'Right Anterior Insula';
Mapping(38,1) = 103;
Volume(38,1) = cell2mat(raw(:, 46));
Active(38,1) = 1;
Symmetry(38,1) = 104;
Tissues(38,1) = 2;

Names{39,1} = 'Left Anterior Insula';
Mapping(39,1) = 104;
Volume(39,1) = cell2mat(raw(:, 47));
Active(39,1) = 1;
Symmetry(39,1) = 103;
Tissues(39,1) = 2;

Names{40,1} = 'Right Anterior Orbital Gyrus';
Mapping(40,1) = 105;
Volume(40,1) = cell2mat(raw(:, 48));
Active(40,1) = 1;
Symmetry(40,1) = 106;
Tissues(40,1) = 2; 

Names{41,1} = 'Left Anterior Orbital Gyrus';
Mapping(41,1) = 106;
Volume(41,1) = cell2mat(raw(:, 49));
Active(41,1) = 1;
Symmetry(41,1) = 105;
Tissues(41,1) = 2; 

Names{42,1} = 'Right Angular Gyrus';
Mapping(42,1) = 107;
Volume(42,1) = cell2mat(raw(:, 50));
Active(42,1) = 1;
Symmetry(42,1) = 108;
Tissues(42,1) = 2; 

Names{43,1} = 'Left Angular Gyrus';
Mapping(43,1) = 108;
Volume(43,1) = cell2mat(raw(:, 51));
Active(43,1) = 1;
Symmetry(43,1) = 107;
Tissues(43,1) = 2; 

Names{44,1} = 'Right Calcarine Cortex';
Mapping(44,1) = 109;
Volume(44,1) = cell2mat(raw(:, 52));
Active(44,1) = 1;
Symmetry(44,1) = 110;
Tissues(44,1) = 2; 

Names{45,1} = 'Left Calcarine Cortex';
Mapping(45,1) = 110;
Volume(45,1) = cell2mat(raw(:, 53));
Active(45,1) = 1;
Symmetry(45,1) = 109;
Tissues(45,1) = 2; 

Names{46,1} = 'Right Central Operculum';
Mapping(46,1) = 113;
Volume(46,1) = cell2mat(raw(:, 54));
Active(46,1) = 1;
Symmetry(46,1) = 114;
Tissues(46,1) = 2; 

Names{47,1} = 'Left Central Operculum';
Mapping(47,1) = 114;
Volume(47,1) = cell2mat(raw(:, 55));
Active(47,1) = 1;
Symmetry(47,1) = 113;
Tissues(47,1) = 2; 

Names{48,1} = 'Right Cuneus';
Mapping(48,1) = 115;
Volume(48,1) = cell2mat(raw(:, 56));
Active(48,1) = 1;
Symmetry(48,1) = 116;
Tissues(48,1) = 2; 

Names{49,1} = 'Left Cuneus';
Mapping(49,1) = 116;
Volume(49,1) = cell2mat(raw(:, 57));
Active(49,1) = 1;
Symmetry(49,1) = 115;
Tissues(49,1) = 2; 

Names{50,1} = 'Right Entorhinal Area';
Mapping(50,1) = 117;
Volume(50,1) = cell2mat(raw(:, 58));
Active(50,1) = 1;
Symmetry(50,1) = 118;
Tissues(50,1) = 2; 

Names{51,1} = 'Left Entorhinal Area';
Mapping(51,1) = 118;
Volume(51,1) = cell2mat(raw(:, 59));
Active(51,1) = 1;
Symmetry(51,1) = 117;
Tissues(51,1) = 2; 

Names{52,1} = 'Right Frontal Operculum';
Mapping(52,1) = 119;
Volume(52,1) = cell2mat(raw(:, 60));
Active(52,1) = 1;
Symmetry(52,1) = 120;
Tissues(52,1) = 2; 

Names{53,1} = 'Left Frontal Operculum';
Mapping(53,1) = 120;
Volume(53,1) = cell2mat(raw(:, 61));
Active(53,1) = 1;
Symmetry(53,1) = 119;
Tissues(53,1) = 2; 

Names{54,1} = 'Right Frontal Pole';
Mapping(54,1) = 121;
Volume(54,1) = cell2mat(raw(:, 62));
Active(54,1) = 1;
Symmetry(54,1) = 122;
Tissues(54,1) = 2; 

Names{55,1} = 'Left Frontal Pole';
Mapping(55,1) = 122;
Volume(55,1) = cell2mat(raw(:, 63));
Active(55,1) = 1;
Symmetry(55,1) = 121;
Tissues(55,1) = 2; 

Names{56,1} = 'Right Fusiform Gyrus';
Mapping(56,1) = 123;
Volume(56,1) = cell2mat(raw(:, 64));
Active(56,1) = 1;
Symmetry(56,1) = 124;
Tissues(56,1) = 2; 

Names{57,1} = 'Left Fusiform Gyrus';
Mapping(57,1) = 124;
Volume(57,1) = cell2mat(raw(:, 65));
Active(57,1) = 1;
Symmetry(57,1) = 123;
Tissues(57,1) = 2; 

Names{58,1} = 'Right Gyrus Rectus';
Mapping(58,1) = 125;
Volume(58,1) = cell2mat(raw(:, 66));
Active(58,1) = 1;
Symmetry(58,1) = 126;
Tissues(58,1) = 2; 

Names{59,1} = 'Left Gyrus Rectus';
Mapping(59,1) = 126;
Volume(59,1) = cell2mat(raw(:, 67));
Active(59,1) = 1;
Symmetry(59,1) = 125;
Tissues(59,1) = 2; 

Names{60,1} = 'Right Inferior Occipital Gyrus';
Mapping(60,1) = 129;
Volume(60,1) = cell2mat(raw(:, 68));
Active(60,1) = 1;
Symmetry(60,1) = 130;
Tissues(60,1) = 2; 

Names{61,1} = 'Left Inferior Occipital Gyrus';
Mapping(61,1) = 130;
Volume(61,1) = cell2mat(raw(:, 69));
Active(61,1) = 1;
Symmetry(61,1) = 129;
Tissues(61,1) = 2; 

Names{62,1} = 'Right Inferior Temporal Gyrus';
Mapping(62,1) = 133;
Volume(62,1) = cell2mat(raw(:, 70));
Active(62,1) = 1;
Symmetry(62,1) = 134;
Tissues(62,1) = 2; 

Names{63,1} = 'Left Inferior Temporal Gyrus';
Mapping(63,1) = 134;
Volume(63,1) = cell2mat(raw(:, 71));
Active(63,1) = 1;
Symmetry(63,1) = 133;
Tissues(63,1) = 2; 

Names{64,1} = 'Right Lingual Gyrus';
Mapping(64,1) = 135;
Volume(64,1) = cell2mat(raw(:, 72));
Active(64,1) = 1;
Symmetry(64,1) = 136;
Tissues(64,1) = 2; 

Names{65,1} = 'Left Lingual Gyrus';
Mapping(65,1) = 136;
Volume(65,1) = cell2mat(raw(:, 73));
Active(65,1) = 1;
Symmetry(65,1) = 135;
Tissues(65,1) = 2; 

Names{66,1} = 'Right Lateral Orbital Gyrus';
Mapping(66,1) = 137;
Volume(66,1) = cell2mat(raw(:, 74));
Active(66,1) = 1;
Symmetry(66,1) = 138;
Tissues(66,1) = 2; 

Names{67,1} = 'Left Lateral Orbital Gyrus';
Mapping(67,1) = 138;
Volume(67,1) = cell2mat(raw(:, 75));
Active(67,1) = 1;
Symmetry(67,1) = 137;
Tissues(67,1) = 2; 

Names{68,1} = 'Right Middle Cingulate Gyrus';
Mapping(68,1) = 139;
Volume(68,1) = cell2mat(raw(:, 76));
Active(68,1) = 1;
Symmetry(68,1) = 140;
Tissues(68,1) = 2; 

Names{69,1} = 'Left Middle Cingulate Gyrus';
Mapping(69,1) = 140;
Volume(69,1) = cell2mat(raw(:, 77));
Active(69,1) = 1;
Symmetry(69,1) = 139;
Tissues(69,1) = 2; 

Names{70,1} = 'Right Medial Frontal Cortex';
Mapping(70,1) = 141;
Volume(70,1) = cell2mat(raw(:, 78));
Active(70,1) = 1;
Symmetry(70,1) = 142;
Tissues(70,1) = 2; 

Names{71,1} = 'Left Medial Frontal Cortex';
Mapping(71,1) = 142;
Volume(71,1) = cell2mat(raw(:, 79));
Active(71,1) = 1;
Symmetry(71,1) = 141;
Tissues(71,1) = 2; 

Names{72,1} = 'Right Middle Frontal Gyrus';
Mapping(72,1) = 143;
Volume(72,1) = cell2mat(raw(:, 80));
Active(72,1) = 1;
Symmetry(72,1) = 144;
Tissues(72,1) = 2; 

Names{73,1} = 'Left Middle Frontal Gyrus';
Mapping(73,1) = 144;
Volume(73,1) = cell2mat(raw(:, 81));
Active(73,1) = 1;
Symmetry(73,1) = 143;
Tissues(73,1) = 2; 

Names{74,1} = 'Right Middle Occipital Gyrus';
Mapping(74,1) = 145;
Volume(74,1) = cell2mat(raw(:, 82));
Active(74,1) = 1;
Symmetry(74,1) = 146;
Tissues(74,1) = 2; 

Names{75,1} = 'Left Middle Occipital Gyrus';
Mapping(75,1) = 146;
Volume(75,1) = cell2mat(raw(:, 83));
Active(75,1) = 1;
Symmetry(75,1) = 145;
Tissues(75,1) = 2; 

Names{76,1} = 'Right Medial Orbital Gyrus';
Mapping(76,1) = 147;
Volume(76,1) = cell2mat(raw(:, 84));
Active(76,1) = 1;
Symmetry(76,1) = 148;
Tissues(76,1) = 2; 

Names{77,1} = 'Left Medial Orbital Gyrus';
Mapping(77,1) = 148;
Volume(77,1) = cell2mat(raw(:, 85));
Active(77,1) = 1;
Symmetry(77,1) = 147;
Tissues(77,1) = 2; 

Names{78,1} = 'Right Postcentral Gyrus Medial Segment';
Mapping(78,1) = 149;
Volume(78,1) = cell2mat(raw(:, 86));
Active(78,1) = 1;
Symmetry(78,1) = 150;
Tissues(78,1) = 2; 

Names{79,1} = 'Left Postcentral Gyrus Medial Segment';
Mapping(79,1) = 150;
Volume(79,1) = cell2mat(raw(:, 87));
Active(79,1) = 1;
Symmetry(79,1) = 149;
Tissues(79,1) = 2; 

Names{80,1} = 'Right Precentral Gyrus Medial Segment';
Mapping(80,1) = 151;
Volume(80,1) = cell2mat(raw(:, 88));
Active(80,1) = 1;
Symmetry(80,1) = 152;
Tissues(80,1) = 2; 

Names{81,1} = 'Left Precentral Gyrus Medial Segment';
Mapping(81,1) = 152;
Volume(81,1) = cell2mat(raw(:, 89));
Active(81,1) = 1;
Symmetry(81,1) = 151;
Tissues(81,1) = 2; 

Names{82,1} = 'Right Superior Frontal Gyrus Medial Segment';
Mapping(82,1) = 153;
Volume(82,1) = cell2mat(raw(:, 90));
Active(82,1) = 1;
Symmetry(82,1) = 154;
Tissues(82,1) = 2; 

Names{83,1} = 'Left Superior Frontal Gyrus Medial Segment';
Mapping(83,1) = 154;
Volume(83,1) = cell2mat(raw(:, 91));
Active(83,1) = 1;
Symmetry(83,1) = 153;
Tissues(83,1) = 2; 

Names{84,1} = 'Right Middle Temporal Gyrus';
Mapping(84,1) = 155;
Volume(84,1) = cell2mat(raw(:, 92));
Active(84,1) = 1;
Symmetry(84,1) = 156;
Tissues(84,1) = 2; 

Names{85,1} = 'Left Middle Temporal Gyrus';
Mapping(85,1) = 156;
Volume(85,1) = cell2mat(raw(:, 93));
Active(85,1) = 1;
Symmetry(85,1) = 155;
Tissues(85,1) = 2; 

Names{86,1} = 'Right Occipital Pole';
Mapping(86,1) = 157;
Volume(86,1) = cell2mat(raw(:, 94));
Active(86,1) = 1;
Symmetry(86,1) = 158;
Tissues(86,1) = 2; 

Names{87,1} = 'Left Occipital Pole';
Mapping(87,1) = 158;
Volume(87,1) = cell2mat(raw(:, 95));
Active(87,1) = 1;
Symmetry(87,1) = 157;
Tissues(87,1) = 2; 

Names{88,1} = 'Right Occipital Fusiform Gyrus';
Mapping(88,1) = 161;
Volume(88,1) = cell2mat(raw(:, 96));
Active(88,1) = 1;
Symmetry(88,1) = 162;
Tissues(88,1) = 2; 

Names{89,1} = 'Left Occipital Fusiform Gyrus';
Mapping(89,1) = 162;
Volume(89,1) = cell2mat(raw(:, 97));
Active(89,1) = 1;
Symmetry(89,1) = 161;
Tissues(89,1) = 2; 

Names{90,1} = 'Right Opercular Part Of The Inferior Frontal Gyrus';
Mapping(90,1) = 163;
Volume(90,1) = cell2mat(raw(:, 98));
Active(90,1) = 1;
Symmetry(90,1) = 164;
Tissues(90,1) = 2; 

Names{91,1} = 'Left Opercular Part Of The Inferior Frontal Gyrus';
Mapping(91,1) = 164;
Volume(91,1) = cell2mat(raw(:, 99));
Active(91,1) = 1;
Symmetry(91,1) = 163;
Tissues(91,1) = 2; 

Names{92,1} = 'Right Orbital Part Of The Inferior Frontal Gyrus';
Mapping(92,1) = 165;
Volume(92,1) = cell2mat(raw(:, 100));
Active(92,1) = 1;
Symmetry(92,1) = 166;
Tissues(92,1) = 2; 

Names{93,1} = 'Left Orbital Part Of The Inferior Frontal Gyrus';
Mapping(93,1) = 166;
Volume(93,1) = cell2mat(raw(:, 101));
Active(93,1) = 1;
Symmetry(93,1) = 165;
Tissues(93,1) = 2; 

Names{94,1} = 'Right Posterior Cingulate Gyrus';
Mapping(94,1) = 167;
Volume(94,1) = cell2mat(raw(:, 102));
Active(94,1) = 1;
Symmetry(94,1) = 168;
Tissues(94,1) = 2; 

Names{95,1} = 'Left Posterior Cingulate Gyrus';
Mapping(95,1) = 168;
Volume(95,1) = cell2mat(raw(:, 103));
Active(95,1) = 1;
Symmetry(95,1) = 167;
Tissues(95,1) = 2; 

Names{96,1} = 'Right Precuneus';
Mapping(96,1) = 169;
Volume(96,1) = cell2mat(raw(:, 104));
Active(96,1) = 1;
Symmetry(96,1) = 170;
Tissues(96,1) = 2; 

Names{97,1} = 'Left Precuneus';
Mapping(97,1) = 170;
Volume(97,1) = cell2mat(raw(:, 105));
Active(97,1) = 1;
Symmetry(97,1) = 169;
Tissues(97,1) = 2; 

Names{98,1} = 'Right Parahippocampal Gyrus';
Mapping(98,1) = 171;
Volume(98,1) = cell2mat(raw(:, 106));
Active(98,1) = 1;
Symmetry(98,1) = 172;
Tissues(98,1) = 2; 

Names{99,1} = 'Left Parahippocampal Gyrus';
Mapping(99,1) = 172;
Volume(99,1) = cell2mat(raw(:, 107));
Active(99,1) = 1;
Symmetry(99,1) = 171;
Tissues(99,1) = 2; 

Names{100,1} = 'Right Posterior Insula';
Mapping(100,1) = 173;
Volume(100,1) = cell2mat(raw(:, 108));
Active(100,1) = 1;
Symmetry(100,1) = 174;
Tissues(100,1) = 2; 

Names{101,1} = 'Left Posterior Insula';
Mapping(101,1) = 174;
Volume(101,1) = cell2mat(raw(:, 109));
Active(101,1) = 1;
Symmetry(101,1) = 173;
Tissues(101,1) = 2; 

Names{102,1} = 'Right Parietal Operculum';
Mapping(102,1) = 175;
Volume(102,1) = cell2mat(raw(:, 110));
Active(102,1) = 1;
Symmetry(102,1) = 176;
Tissues(102,1) = 2; 

Names{103,1} = 'Left Parietal Operculum';
Mapping(103,1) = 176;
Volume(103,1) = cell2mat(raw(:, 111));
Active(103,1) = 1;
Symmetry(103,1) = 175;
Tissues(103,1) = 2; 

Names{104,1} = 'Right Postcentral Gyrus';
Mapping(104,1) = 177;
Volume(104,1) = cell2mat(raw(:, 112));
Active(104,1) = 1;
Symmetry(104,1) = 178;
Tissues(104,1) = 2; 

Names{105,1} = 'Left Postcentral Gyrus';
Mapping(105,1) = 178;
Volume(105,1) = cell2mat(raw(:, 113));
Active(105,1) = 1;
Symmetry(105,1) = 177;
Tissues(105,1) = 2; 

Names{106,1} = 'Right Posterior Orbital Gyrus';
Mapping(106,1) = 179;
Volume(106,1) = cell2mat(raw(:, 114));
Active(106,1) = 1;
Symmetry(106,1) = 180;
Tissues(106,1) = 2; 

Names{107,1} = 'Left Posterior Orbital Gyrus';
Mapping(107,1) = 180;
Volume(107,1) = cell2mat(raw(:, 115));
Active(107,1) = 1;
Symmetry(107,1) = 179;
Tissues(107,1) = 2; 

Names{108,1} = 'Right Planum Polare';
Mapping(108,1) = 181;
Volume(108,1) = cell2mat(raw(:, 116));
Active(108,1) = 1;
Symmetry(108,1) = 182;
Tissues(108,1) = 2; 

Names{109,1} = 'Left Planum Polare';
Mapping(109,1) = 182;
Volume(109,1) = cell2mat(raw(:, 117));
Active(109,1) = 1;
Symmetry(109,1) = 181;
Tissues(109,1) = 2; 

Names{110,1} = 'Right Precentral Gyrus';
Mapping(110,1) = 183;
Volume(110,1) = cell2mat(raw(:, 118));
Active(110,1) = 1;
Symmetry(110,1) = 184;
Tissues(110,1) = 2; 

Names{111,1} = 'Left Precentral Gyrus';
Mapping(111,1) = 184;
Volume(111,1) = cell2mat(raw(:, 119));
Active(111,1) = 1;
Symmetry(111,1) = 183;
Tissues(111,1) = 2; 

Names{112,1} = 'Right Planum Temporale';
Mapping(112,1) = 185;
Volume(112,1) = cell2mat(raw(:, 120));
Active(112,1) = 1;
Symmetry(112,1) = 186;
Tissues(112,1) = 2; 

Names{113,1} = 'Left Planum Temporale';
Mapping(113,1) = 186;
Volume(113,1) = cell2mat(raw(:, 121));
Active(113,1) = 1;
Symmetry(113,1) = 185;
Tissues(113,1) = 2; 

Names{114,1} = 'Right Subcallosal Area';
Mapping(114,1) = 187;
Volume(114,1) = cell2mat(raw(:, 122));
Active(114,1) = 1;
Symmetry(114,1) = 188;
Tissues(114,1) = 2; 

Names{115,1} = 'Left Subcallosal Area';
Mapping(115,1) = 188;
Volume(115,1) = cell2mat(raw(:, 123));
Active(115,1) = 1;
Symmetry(115,1) = 187;
Tissues(115,1) = 2; 

Names{116,1} = 'Right Superior Frontal Gyrus';
Mapping(116,1) = 191;
Volume(116,1) = cell2mat(raw(:, 124));
Active(116,1) = 1;
Symmetry(116,1) = 192;
Tissues(116,1) = 2; 

Names{117,1} = 'Left Superior Frontal Gyrus';
Mapping(117,1) = 192;
Volume(117,1) = cell2mat(raw(:, 125));
Active(117,1) = 1;
Symmetry(117,1) = 191;
Tissues(117,1) = 2; 

Names{118,1} = 'Right Supplementary Motor Cortex';
Mapping(118,1) = 193;
Volume(118,1) = cell2mat(raw(:, 126));
Active(118,1) = 1;
Symmetry(118,1) = 194;
Tissues(118,1) = 2; 

Names{119,1} = 'Left Supplementary Motor Cortex';
Mapping(119,1) = 194;
Volume(119,1) = cell2mat(raw(:, 127));
Active(119,1) = 1;
Symmetry(119,1) = 193;
Tissues(119,1) = 2; 

Names{120,1} = 'Right Supramarginal Gyrus';
Mapping(120,1) = 195;
Volume(120,1) = cell2mat(raw(:, 128));
Active(120,1) = 1;
Symmetry(120,1) = 196;
Tissues(120,1) = 2; 

Names{121,1} = 'Left Supramarginal Gyrus';
Mapping(121,1) = 196;
Volume(121,1) = cell2mat(raw(:, 129));
Active(121,1) = 1;
Symmetry(121,1) = 195;
Tissues(121,1) = 2; 

Names{122,1} = 'Right Superior Occipital Gyrus';
Mapping(122,1) = 197;
Volume(122,1) = cell2mat(raw(:, 130));
Active(122,1) = 1;
Symmetry(122,1) = 198;
Tissues(122,1) = 2; 

Names{123,1} = 'Left Superior Occipital Gyrus';
Mapping(123,1) = 198;
Volume(123,1) = cell2mat(raw(:, 131));
Active(123,1) = 1;
Symmetry(123,1) = 197;
Tissues(123,1) = 2; 

Names{124,1} = 'Right Superior Parietal Lobule';
Mapping(124,1) = 199;
Volume(124,1) = cell2mat(raw(:, 132));
Active(124,1) = 1;
Symmetry(124,1) = 200;
Tissues(124,1) = 2; 

Names{125,1} = 'Left Superior Parietal Lobule';
Mapping(125,1) = 200;
Volume(125,1) = cell2mat(raw(:, 133));
Active(125,1) = 1;
Symmetry(125,1) = 199;
Tissues(125,1) = 2; 

Names{126,1} = 'Right Superior Temporal Gyrus';
Mapping(126,1) = 201;
Volume(126,1) = cell2mat(raw(:, 134));
Active(126,1) = 1;
Symmetry(126,1) = 202;
Tissues(126,1) = 2; 

Names{127,1} = 'Left Superior Temporal Gyrus';
Mapping(127,1) = 202;
Volume(127,1) = cell2mat(raw(:, 135));
Active(127,1) = 1;
Symmetry(127,1) = 201;
Tissues(127,1) = 2; 

Names{128,1} = 'Right Temporal Pole';
Mapping(128,1) = 203;
Volume(128,1) = cell2mat(raw(:, 136));
Active(128,1) = 1;
Symmetry(128,1) = 204;
Tissues(128,1) = 2; 

Names{129,1} = 'Left Temporal Pole';
Mapping(129,1) = 204;
Volume(129,1) = cell2mat(raw(:, 137));
Active(129,1) = 1;
Symmetry(129,1) = 203;
Tissues(129,1) = 2; 

Names{130,1} = 'Right Triangular Part Of The Inferior Frontal Gyrus';
Mapping(130,1) = 205;
Volume(130,1) = cell2mat(raw(:, 138));
Active(130,1) = 1;
Symmetry(130,1) = 206;
Tissues(130,1) = 2; 

Names{131,1} = 'Left Triangular Part Of The Inferior Frontal Gyrus';
Mapping(131,1) = 206;
Volume(131,1) = cell2mat(raw(:, 139));
Active(131,1) = 1;
Symmetry(131,1) = 205;
Tissues(131,1) = 2; 

Names{132,1} = 'Right Transverse Temporal Gyrus';
Mapping(132,1) = 207;
Volume(132,1) = cell2mat(raw(:, 140));
Active(132,1) = 1;
Symmetry(132,1) = 208;
Tissues(132,1) = 2; 

Names{133,1} = 'Left Transverse Temporal Gyrus';
Mapping(133,1) = 208;
Volume(133,1) = cell2mat(raw(:, 141));
Active(133,1) = 1;
Symmetry(133,1) = 207;
Tissues(133,1) = 2; 


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp me;
Active = logical(Active);

end
